### ISSUE TITLE
practice: filtered get apis do not work

### ISSUE THREAD

**Issue by benedikt255** [stan1025/VDILoewen#1]
It seems like the filtered getApis (GET:    "/practices/practiceTypes"
Param:  practiceType: requested Practice Type
-> Returns all the Practices Entries of the defined Type

GET:    "/practices/requestTypes
Param:  requestType: requested Request Type
-> Returns all the Practices Entries of the defined Type

GET: "/practices/requestTypes/user"
Param:  requestTypes: requested Request Type
Param: UserID: User Identificator
-> returns all the entries of this user)

do not parse the parameters correctly. Maybe try query instead of body;)

**Comment by stan1025** [comment]
API Route Names had a "s" charakter at the end but it should be named as requestType and not Types. This error results also in a parameter with a s at the end. 

Names corrected
